FROM node:20-alpine
RUN npm install -g pnpm
RUN mkdir -p /opt/app
RUN mkdir -p /opt/app/src
WORKDIR /opt/app
COPY tsconfig.json ./
COPY .env ./
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
COPY src/ ./src/
EXPOSE 3000
CMD [ "pnpm", "start"]
